/*
    ! FINISH BY APRIL

    * 6 / 9 COMPLETED

    TODO: MAKE ORDERS PAGE
    * COMPLETED

    TODO: CLOUD FUNCTIONS FOR STRIPE CHECKOUT AND STRIPE WEBHOOK
    ! POSTPONED (BILLING ACCOUNT FOR FIREBASE FUNCTIONS)

    TODO: CURRENCY SUPPORT: CAD, EURO, USD
    * COMPLETED

    TODO: MODAL ANIMATIONS

    TODO: USER SHOPPING CART
    * COMPLETED

    TODO: BUY NOW BUTTON FOR SINGLE POSTS
    * COMPLETED

    TODO: CHECKOUT WITH CART FOR MULTI POSTS
    ! POSTPONED (BILLING ACCOUNT FOR FIREBASE FUNCTIONS)

    TODO: SUPPORT FOR MULTI IMAGES
    * COMPLETED

    TODO: MAKE SEARCH ENGINE
    * COMPLETED
*/

export const x = null