/*
    ! FINISH BY APRIL

    * 13 / 13 COMPLETED
    TODO: MAKE ORDERS PAGE
    * COMPLETED

    TODO: CLOUD FUNCTIONS FOR STRIPE CHECKOUT AND STRIPE WEBHOOK
    ! POSTPONED (BILLING ACCOUNT FOR FIREBASE FUNCTIONS)

    TODO: CURRENCY SUPPORT: CAD, EURO, USD
    * COMPLETED

    TODO: USER SHOPPING CART
    * COMPLETED

    TODO: BUY NOW BUTTON FOR SINGLE POSTS
    * COMPLETED

    TODO: CHECKOUT WITH CART FOR MULTI POSTS
    * COMPLETED

    TODO: SUPPORT FOR MULTI IMAGES
    * COMPLETED

    TODO: MAKE SEARCH ENGINE
    * COMPLETED

    TODO: MAKE USER PROFILE PAGES
    * COMPLETED

    TODO: RANDOM AVATARS FOR NEW USERS
    * COMPLETED

    TODO: CONFIGURE FIREBASE HOSTING & NEXT BUILD + NEXT EXPORT
    * COMPLETED

    TODO: MAKE BASIC CYPRESS TESTS
    * COMPLETED

    TODO: MAKE VIEWING SYSTEM AND ADD PAGE FOR MOST VIEWED POSTS
    * COMPLETED
*/

export const x = null